# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bubbly_pom/bubbly_pom.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(820, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 100))
        self.frame.setStyleSheet("QFrame {\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(250, 250, 250, 91), stop:1 rgba(255, 255, 255, 192));\n"
"border-bottom: 1px solid darkgray; \n"
"}\n"
"\n"
"QToolButton {\n"
"//background-color: none;\n"
"border: none;\n"
"}\n"
"\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(118, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.timer_tab_btn = QtWidgets.QToolButton(self.frame)
        self.timer_tab_btn.setIconSize(QtCore.QSize(64, 64))
        self.timer_tab_btn.setObjectName("timer_tab_btn")
        self.horizontalLayout.addWidget(self.timer_tab_btn)
        spacerItem1 = QtWidgets.QSpacerItem(119, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.notes_tab_btn = QtWidgets.QToolButton(self.frame)
        self.notes_tab_btn.setIconSize(QtCore.QSize(64, 64))
        self.notes_tab_btn.setObjectName("notes_tab_btn")
        self.horizontalLayout.addWidget(self.notes_tab_btn)
        spacerItem2 = QtWidgets.QSpacerItem(158, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pinterest_tab_btn = QtWidgets.QToolButton(self.frame)
        self.pinterest_tab_btn.setIconSize(QtCore.QSize(64, 64))
        self.pinterest_tab_btn.setObjectName("pinterest_tab_btn")
        self.horizontalLayout.addWidget(self.pinterest_tab_btn)
        spacerItem3 = QtWidgets.QSpacerItem(119, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.soundcloud_tab_btn = QtWidgets.QToolButton(self.frame)
        self.soundcloud_tab_btn.setIconSize(QtCore.QSize(64, 64))
        self.soundcloud_tab_btn.setObjectName("soundcloud_tab_btn")
        self.horizontalLayout.addWidget(self.soundcloud_tab_btn)
        spacerItem4 = QtWidgets.QSpacerItem(118, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout.addWidget(self.frame)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.timer_tab = QtWidgets.QWidget()
        self.timer_tab.setObjectName("timer_tab")
        self.gridLayout = QtWidgets.QGridLayout(self.timer_tab)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.timer_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(180, 0))
        self.label.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.pom_dur_lcd = QtWidgets.QLCDNumber(self.timer_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pom_dur_lcd.sizePolicy().hasHeightForWidth())
        self.pom_dur_lcd.setSizePolicy(sizePolicy)
        self.pom_dur_lcd.setMaximumSize(QtCore.QSize(16777215, 60))
        self.pom_dur_lcd.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pom_dur_lcd.setLineWidth(1)
        self.pom_dur_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.pom_dur_lcd.setObjectName("pom_dur_lcd")
        self.verticalLayout_2.addWidget(self.pom_dur_lcd)
        self.pom_dial = QtWidgets.QDial(self.timer_tab)
        self.pom_dial.setMinimum(25)
        self.pom_dial.setMaximum(50)
        self.pom_dial.setSingleStep(5)
        self.pom_dial.setOrientation(QtCore.Qt.Horizontal)
        self.pom_dial.setNotchesVisible(True)
        self.pom_dial.setObjectName("pom_dial")
        self.verticalLayout_2.addWidget(self.pom_dial)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.timer_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(180, 0))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.short_brk_lcd = QtWidgets.QLCDNumber(self.timer_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.short_brk_lcd.sizePolicy().hasHeightForWidth())
        self.short_brk_lcd.setSizePolicy(sizePolicy)
        self.short_brk_lcd.setMaximumSize(QtCore.QSize(16777215, 60))
        self.short_brk_lcd.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.short_brk_lcd.setLineWidth(1)
        self.short_brk_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.short_brk_lcd.setProperty("intValue", 0)
        self.short_brk_lcd.setObjectName("short_brk_lcd")
        self.verticalLayout_3.addWidget(self.short_brk_lcd)
        self.short_brk_dial = QtWidgets.QDial(self.timer_tab)
        self.short_brk_dial.setMinimum(3)
        self.short_brk_dial.setMaximum(25)
        self.short_brk_dial.setSingleStep(1)
        self.short_brk_dial.setNotchesVisible(True)
        self.short_brk_dial.setObjectName("short_brk_dial")
        self.verticalLayout_3.addWidget(self.short_brk_dial)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.timer_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(180, 0))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.long_brk_lcd = QtWidgets.QLCDNumber(self.timer_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.long_brk_lcd.sizePolicy().hasHeightForWidth())
        self.long_brk_lcd.setSizePolicy(sizePolicy)
        self.long_brk_lcd.setMaximumSize(QtCore.QSize(16777215, 60))
        self.long_brk_lcd.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.long_brk_lcd.setLineWidth(1)
        self.long_brk_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.long_brk_lcd.setObjectName("long_brk_lcd")
        self.verticalLayout_4.addWidget(self.long_brk_lcd)
        self.long_brk_dial = QtWidgets.QDial(self.timer_tab)
        self.long_brk_dial.setMinimum(10)
        self.long_brk_dial.setMaximum(50)
        self.long_brk_dial.setSingleStep(1)
        self.long_brk_dial.setNotchesVisible(True)
        self.long_brk_dial.setObjectName("long_brk_dial")
        self.verticalLayout_4.addWidget(self.long_brk_dial)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.timer_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(180, 0))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.long_brk_freq_lcd = QtWidgets.QLCDNumber(self.timer_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.long_brk_freq_lcd.sizePolicy().hasHeightForWidth())
        self.long_brk_freq_lcd.setSizePolicy(sizePolicy)
        self.long_brk_freq_lcd.setMaximumSize(QtCore.QSize(16777215, 60))
        self.long_brk_freq_lcd.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.long_brk_freq_lcd.setLineWidth(1)
        self.long_brk_freq_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.long_brk_freq_lcd.setObjectName("long_brk_freq_lcd")
        self.verticalLayout_5.addWidget(self.long_brk_freq_lcd)
        self.long_brk_freq_dial = QtWidgets.QDial(self.timer_tab)
        self.long_brk_freq_dial.setMinimum(2)
        self.long_brk_freq_dial.setMaximum(10)
        self.long_brk_freq_dial.setSingleStep(1)
        self.long_brk_freq_dial.setNotchesVisible(True)
        self.long_brk_freq_dial.setObjectName("long_brk_freq_dial")
        self.verticalLayout_5.addWidget(self.long_brk_freq_dial)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.start_timer_btn = QtWidgets.QPushButton(self.timer_tab)
        self.start_timer_btn.setObjectName("start_timer_btn")
        self.horizontalLayout_3.addWidget(self.start_timer_btn)
        self.stop_timer_btn = QtWidgets.QPushButton(self.timer_tab)
        self.stop_timer_btn.setObjectName("stop_timer_btn")
        self.horizontalLayout_3.addWidget(self.stop_timer_btn)
        self.next_timer_btn = QtWidgets.QPushButton(self.timer_tab)
        self.next_timer_btn.setObjectName("next_timer_btn")
        self.horizontalLayout_3.addWidget(self.next_timer_btn)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.curr_timer_progress = QtWidgets.QProgressBar(self.timer_tab)
        self.curr_timer_progress.setProperty("value", 0)
        self.curr_timer_progress.setObjectName("curr_timer_progress")
        self.horizontalLayout_4.addWidget(self.curr_timer_progress)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.timer_tab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.add_note_btn = QtWidgets.QPushButton(self.tab)
        self.add_note_btn.setFlat(False)
        self.add_note_btn.setObjectName("add_note_btn")
        self.verticalLayout_11.addWidget(self.add_note_btn)
        self.notes_table = QtWidgets.QTableWidget(self.tab)
        self.notes_table.setRowCount(0)
        self.notes_table.setColumnCount(2)
        self.notes_table.setObjectName("notes_table")
        self.notes_table.horizontalHeader().setCascadingSectionResizes(False)
        self.notes_table.horizontalHeader().setStretchLastSection(False)
        self.verticalLayout_11.addWidget(self.notes_table)
        self.delete_note_btn = QtWidgets.QPushButton(self.tab)
        self.delete_note_btn.setEnabled(False)
        self.delete_note_btn.setObjectName("delete_note_btn")
        self.verticalLayout_11.addWidget(self.delete_note_btn)
        self.gridLayout_4.addLayout(self.verticalLayout_11, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.pinterest_tab = QtWidgets.QWidget()
        self.pinterest_tab.setObjectName("pinterest_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.pinterest_tab)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.auto_preview_pins_checkbox = QtWidgets.QCheckBox(self.pinterest_tab)
        self.auto_preview_pins_checkbox.setObjectName("auto_preview_pins_checkbox")
        self.verticalLayout_7.addWidget(self.auto_preview_pins_checkbox)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.pinterest_tab)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.pin_link_line_edit = QtWidgets.QLineEdit(self.pinterest_tab)
        self.pin_link_line_edit.setObjectName("pin_link_line_edit")
        self.horizontalLayout_5.addWidget(self.pin_link_line_edit)
        self.add_pin_collection_btn = QtWidgets.QPushButton(self.pinterest_tab)
        self.add_pin_collection_btn.setObjectName("add_pin_collection_btn")
        self.horizontalLayout_5.addWidget(self.add_pin_collection_btn)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.pin_list = QtWidgets.QListWidget(self.pinterest_tab)
        self.pin_list.setObjectName("pin_list")
        self.verticalLayout_7.addWidget(self.pin_list)
        self.gridLayout_2.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.tabWidget.addTab(self.pinterest_tab, "")
        self.soundcloud_tab = QtWidgets.QWidget()
        self.soundcloud_tab.setObjectName("soundcloud_tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.soundcloud_tab)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_9 = QtWidgets.QLabel(self.soundcloud_tab)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.sc_playlist_link_line_edit = QtWidgets.QLineEdit(self.soundcloud_tab)
        self.sc_playlist_link_line_edit.setObjectName("sc_playlist_link_line_edit")
        self.horizontalLayout_6.addWidget(self.sc_playlist_link_line_edit)
        self.add_sc_playlist_to_work_btn = QtWidgets.QPushButton(self.soundcloud_tab)
        self.add_sc_playlist_to_work_btn.setObjectName("add_sc_playlist_to_work_btn")
        self.horizontalLayout_6.addWidget(self.add_sc_playlist_to_work_btn)
        self.add_sc_playlist_to_break_btn = QtWidgets.QPushButton(self.soundcloud_tab)
        self.add_sc_playlist_to_break_btn.setObjectName("add_sc_playlist_to_break_btn")
        self.horizontalLayout_6.addWidget(self.add_sc_playlist_to_break_btn)
        self.verticalLayout_10.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_10 = QtWidgets.QLabel(self.soundcloud_tab)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_9.addWidget(self.label_10)
        self.sc_work_list = QtWidgets.QListView(self.soundcloud_tab)
        self.sc_work_list.setObjectName("sc_work_list")
        self.verticalLayout_9.addWidget(self.sc_work_list)
        self.horizontalLayout_7.addLayout(self.verticalLayout_9)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_11 = QtWidgets.QLabel(self.soundcloud_tab)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_8.addWidget(self.label_11)
        self.sc_break_list = QtWidgets.QListView(self.soundcloud_tab)
        self.sc_break_list.setObjectName("sc_break_list")
        self.verticalLayout_8.addWidget(self.sc_break_list)
        self.horizontalLayout_7.addLayout(self.verticalLayout_8)
        self.verticalLayout_10.addLayout(self.horizontalLayout_7)
        self.line = QtWidgets.QFrame(self.soundcloud_tab)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_10.addWidget(self.line)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.prev_btn = QtWidgets.QPushButton(self.soundcloud_tab)
        self.prev_btn.setObjectName("prev_btn")
        self.horizontalLayout_8.addWidget(self.prev_btn)
        self.play_btn = QtWidgets.QPushButton(self.soundcloud_tab)
        self.play_btn.setObjectName("play_btn")
        self.horizontalLayout_8.addWidget(self.play_btn)
        self.pause_btn = QtWidgets.QPushButton(self.soundcloud_tab)
        self.pause_btn.setObjectName("pause_btn")
        self.horizontalLayout_8.addWidget(self.pause_btn)
        self.stop_btn = QtWidgets.QPushButton(self.soundcloud_tab)
        self.stop_btn.setObjectName("stop_btn")
        self.horizontalLayout_8.addWidget(self.stop_btn)
        self.next_btn = QtWidgets.QPushButton(self.soundcloud_tab)
        self.next_btn.setObjectName("next_btn")
        self.horizontalLayout_8.addWidget(self.next_btn)
        self.label_12 = QtWidgets.QLabel(self.soundcloud_tab)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_8.addWidget(self.label_12)
        self.curr_song_name = QtWidgets.QLineEdit(self.soundcloud_tab)
        self.curr_song_name.setObjectName("curr_song_name")
        self.horizontalLayout_8.addWidget(self.curr_song_name)
        self.verticalLayout_10.addLayout(self.horizontalLayout_8)
        self.gridLayout_3.addLayout(self.verticalLayout_10, 0, 0, 1, 1)
        self.tabWidget.addTab(self.soundcloud_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 820, 28))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.pom_dial.valueChanged['int'].connect(self.pom_dur_lcd.display)
        self.short_brk_dial.valueChanged['int'].connect(self.short_brk_lcd.display)
        self.long_brk_dial.valueChanged['int'].connect(self.long_brk_lcd.display)
        self.long_brk_freq_dial.valueChanged['int'].connect(self.long_brk_freq_lcd.display)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BubblyPom"))
        self.timer_tab_btn.setText(_translate("MainWindow", "..."))
        self.notes_tab_btn.setText(_translate("MainWindow", "..."))
        self.pinterest_tab_btn.setText(_translate("MainWindow", "..."))
        self.soundcloud_tab_btn.setText(_translate("MainWindow", "..."))
        self.label.setText(_translate("MainWindow", "Pomodoro Duration"))
        self.label_2.setText(_translate("MainWindow", "Short Break Duration"))
        self.label_3.setText(_translate("MainWindow", "Long Break Duration"))
        self.label_7.setText(_translate("MainWindow", "Long Break Frequency"))
        self.start_timer_btn.setText(_translate("MainWindow", "Start"))
        self.stop_timer_btn.setText(_translate("MainWindow", "Stop"))
        self.next_timer_btn.setText(_translate("MainWindow", "Next"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.timer_tab), _translate("MainWindow", "Timer settings"))
        self.add_note_btn.setText(_translate("MainWindow", "Add new Note/Idea"))
        self.notes_table.setSortingEnabled(True)
        self.delete_note_btn.setText(_translate("MainWindow", "Delete Selected"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Notes and Ideas"))
        self.auto_preview_pins_checkbox.setText(_translate("MainWindow", "Automatically Preveiw Pins in Break Time"))
        self.label_8.setText(_translate("MainWindow", "Collection link:"))
        self.add_pin_collection_btn.setText(_translate("MainWindow", "Add"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pinterest_tab), _translate("MainWindow", "Pinterest Settings"))
        self.label_9.setText(_translate("MainWindow", "Playlist Link:"))
        self.add_sc_playlist_to_work_btn.setText(_translate("MainWindow", "Add to Work List"))
        self.add_sc_playlist_to_break_btn.setText(_translate("MainWindow", "Add to Break List"))
        self.label_10.setText(_translate("MainWindow", "Work List"))
        self.label_11.setText(_translate("MainWindow", "Break List"))
        self.prev_btn.setText(_translate("MainWindow", "Previous"))
        self.play_btn.setText(_translate("MainWindow", "Play"))
        self.pause_btn.setText(_translate("MainWindow", "Pause"))
        self.stop_btn.setText(_translate("MainWindow", "Stop"))
        self.next_btn.setText(_translate("MainWindow", "Next"))
        self.label_12.setText(_translate("MainWindow", "Currently Playing"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.soundcloud_tab), _translate("MainWindow", "Soundcloud Settings"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

